"""Generate downloadable reports in various formats."""
from datetime import datetime
from typing import Dict, Any


class ReportGenerator:
    """Generate marketing research reports."""

    def generate_markdown(
        self,
        company_name: str,
        analysis_result: str,
        timestamp: datetime
    ) -> str:
        """
        Generate a Markdown report.

        Args:
            company_name: Company name
            analysis_result: Claude's analysis result
            timestamp: Report generation timestamp

        Returns:
            Markdown formatted report
        """
        report_lines = []

        # Header
        report_lines.append(f"# Marketing Research Report: {company_name}")
        report_lines.append("")
        report_lines.append(f"**Generated by:** Marketing Research AI (MachinePoem.agency)")
        report_lines.append(f"**Date:** {timestamp.strftime('%B %d, %Y at %I:%M %p')}")
        report_lines.append("")
        report_lines.append("---")
        report_lines.append("")

        # Analysis content
        report_lines.append(analysis_result)

        # Footer
        report_lines.append("")
        report_lines.append("---")
        report_lines.append("")
        report_lines.append("## About This Report")
        report_lines.append("")
        report_lines.append("This report was generated using AI-powered marketing research tools that:")
        report_lines.append("")
        report_lines.append("- Auto-detected competitors using web search")
        report_lines.append("- Analyzed public ad data from Meta Ad Library and other sources")
        report_lines.append("- Detected this week's viral trends across multiple platforms")
        report_lines.append("- Used Claude AI to generate strategic insights and creative ideas")
        report_lines.append("")
        report_lines.append("**Powered by:** Claude AI (Anthropic)")
        report_lines.append(f"**Model:** Claude Sonnet 4.5")
        report_lines.append("")
        report_lines.append("**Built for:** MachinePoem.agency")
        report_lines.append("")
        report_lines.append("---")
        report_lines.append("")
        report_lines.append("*This report is for internal use only. All recommendations should be reviewed and adapted by your marketing team before implementation.*")

        return "\n".join(report_lines)

    def generate_html(
        self,
        company_name: str,
        analysis_result: str,
        timestamp: datetime
    ) -> str:
        """
        Generate an HTML report.

        Args:
            company_name: Company name
            analysis_result: Claude's analysis result
            timestamp: Report generation timestamp

        Returns:
            HTML formatted report
        """
        # Convert markdown to HTML (basic conversion)
        html_content = analysis_result.replace('\n', '<br>\n')

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Marketing Research Report: {company_name}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }}
        h1 {{
            color: #1a1a1a;
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #2c3e50;
            margin-top: 30px;
        }}
        .header {{
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }}
        .footer {{
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-top: 50px;
            font-size: 0.9em;
            color: #666;
        }}
        .content {{
            padding: 20px 0;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Marketing Research Report: {company_name}</h1>
        <p><strong>Generated by:</strong> Marketing Research AI (MachinePoem.agency)</p>
        <p><strong>Date:</strong> {timestamp.strftime('%B %d, %Y at %I:%M %p')}</p>
    </div>

    <div class="content">
        {html_content}
    </div>

    <div class="footer">
        <h2>About This Report</h2>
        <p>This report was generated using AI-powered marketing research tools that:</p>
        <ul>
            <li>Auto-detected competitors using web search</li>
            <li>Analyzed public ad data from Meta Ad Library and other sources</li>
            <li>Detected this week's viral trends across multiple platforms</li>
            <li>Used Claude AI to generate strategic insights and creative ideas</li>
        </ul>
        <p><strong>Powered by:</strong> Claude AI (Anthropic) - Claude Sonnet 4.5</p>
        <p><strong>Built for:</strong> MachinePoem.agency</p>
        <hr>
        <p><em>This report is for internal use only. All recommendations should be reviewed and adapted by your marketing team before implementation.</em></p>
    </div>
</body>
</html>"""

        return html

    def generate_json(
        self,
        company_name: str,
        company_url: str,
        competitor_urls: list,
        ad_data: Dict[str, Any],
        trends_data: Dict[str, Any],
        analysis_result: str,
        timestamp: datetime
    ) -> str:
        """
        Generate a JSON export of all data.

        Args:
            company_name: Company name
            company_url: Company URL
            competitor_urls: List of competitor URLs
            ad_data: Ad data
            trends_data: Trends data
            analysis_result: Claude's analysis
            timestamp: Report timestamp

        Returns:
            JSON formatted data
        """
        import json

        data = {
            'report_metadata': {
                'company_name': company_name,
                'company_url': company_url,
                'generated_at': timestamp.isoformat(),
                'generator': 'Marketing Research AI (MachinePoem.agency)',
                'model': 'Claude Sonnet 4.5'
            },
            'competitors': competitor_urls,
            'ad_data': ad_data,
            'trends_data': trends_data,
            'analysis': analysis_result
        }

        return json.dumps(data, indent=2)
